### ISSUE TITLE
use @sensebox/eslint-config-sensebox

### ISSUE THREAD

**Issue by noerw** [sensebox/ttn-osem-integration#14]
[`yarn add --tilde --dev @sensebox/eslint-config-sensebox eslint@4.16.0`](https://github.com/sensebox/eslint-config-senseBox)

**Comment by ubergesundheit** [comment]
You propably want to run it without specifying the `@4.16.0`. It installs only that version while there is already a newer one. I have to change it in the readme of the other repository
