### ISSUE TITLE
use @sensebox/opensensemap-api-models

### ISSUE THREAD

**Issue by noerw** [sensebox/ttn-osem-integration#15]
[src](https://github.com/sensebox/openSenseMap-API/tree/master/packages/models)

probably requires new configuration strategy

**Comment by ubergesundheit** [comment]
correct

**Comment by mpfeil** [comment]
installed `@sensebox/opensensemap-api-models` in faebf3a28180f62746ea474619c7941a5d1ac4b9

changed configuration in 0441dd03dcea4b481af5aaaf36e378b50c90e257
