### ISSUE TITLE
Editing thethingsnetwork parameters via osem form, json is not available as decoding profile

### ISSUE THREAD

**Issue by Cinezaster** [sensebox/ttn-osem-integration#9]
I'm using the form on https://opensensemap.org/account/xxxxMY_BOX_IDxxxxxxx/edit/ttn
The Decoding Profile only has 
- sensebox:home
- Lora serialization

Since I decode my message in ttn I would like to use `payload_fields `. In that case I need the json decoding profile
I already tried some configurations with the Lora serialization. But no data appears. 

I someone could explain me what I'm doing wrong.

I have a Lora version of the luftdaten.info sensor and the output is PM10 and PM2.5.

**Comment by ubergesundheit** [comment]
Hi @Cinezaster,

thanks for using the TTN integration! Could you paste an example of your `payload_fields` object here?

Also, have you configured the HTTP Integration on the thethingsnetwork console?

In order to be understood by the openSenseMap, you have to use one of the json formats described here: https://docs.opensensemap.org/#api-Measurements-postNewMeasurements

I think it would be possible to just add the required fields to the `payload_fields` in the decoder in the thingsnetwork console.

Ping @noerw

**Comment by noerw** [comment]
Indeed, the `json` option needs to be added in the frontend, I will so asap

Meanwhile you could set the `json` decoding profile directly via the API, by sending a PUT request to `https://api.opensensemap.org/boxes/<your-box-id>`.
This route requires authentication, via a JWT token that you obtain by calling https://api.opensensemap.org/users/login` the following request first.

With `curl` and [`jq`](https://stedolan.github.io/jq/) this would look like this:

```bash
OSEM_API=https://api.opensensemap.org
OSEM_BOX=YOURBOXID
OSEM_USER=YOUREMAIL
OSEM_PASS=YOURPASSWORD
TTN_DEVID=YOURDEV
TTN_APPID=YOURAPP

# login
OSEM_TOKEN=$(curl -H "content-type: application/json" $OSEM_API/users/sign-in -d '{"email":"'$OSEM_USER'","password":"'$OSEM_PASS'"}' | jq .token  | tr -d '"')

# set TTN profile to json
curl -H "content-type: application/json" \
  -H "Authorization: Bearer $OSEM_TOKEN" \
  -XPUT $OSEM_API/boxes/$OSEM_BOX \
  -d '{"ttn": { "profile": "json", "app_id": "'$TTN_APPID'", "dev_id": "'$TTN_DEVID'" } }'
```

**Comment by Cinezaster** [comment]
hi @ubergesundheit 

I tried something like this, no clue if this is correct or not. 
```
[
{ "sensor_type": "SDS011", "sensor_title": "PM10", "payload_fields": "SDS_P1" },
{ "sensor_type": "SDS011", "sensor_title": "PM2.5", "payload_fields": "SDS_P2" }
]
```
And I did not configure a http integration. I thought osem would connect to the broker and uses my appId and deviceId to find the correct data. 
It makes sense, but is not clear from the documentation.

Thanks for helping

**Comment by noerw** [comment]
No, currently the integration works as a HTTP webhook, so you need to configure the HTTP Integration to point to `POST https://ttn.opensensemap.org/v1.1`

You need to make sure that your payload function results in a JSON format [that is understood by the osem API](https://docs.opensensemap.org/#api-Measurements-postNewMeasurements), eg. something like this would work:

```json
{"sensorid": value, "sensorid": value}
```

An advanced payload function using [lora-serialization](https://github.com/thesolarnomad/lora-serialization) encoding on the node could look like [this](https://gist.github.com/noerw/96712a854f496ee8dd8386fde526fe93)

**Comment by Cinezaster** [comment]
I'm using the luftdaten Format:
```
{
  "sensordatavalues": [
    {
      "value_type": "SDS_P1",
      "value": "5.38"
    },
    {
      "value_type": "SDS_P2",
      "value": "4.98"
    }
  ]
}
```

**Comment by ubergesundheit** [comment]
Sorry, this one only works through the traditional HTTP Rest endpoint via POST for now.

**Comment by Cinezaster** [comment]
Ok.
My decode function:
```
function Decoder(bytes, port) {
  var decoded = {
    "596cb2638ecc890010075e53" : ((bytes[2]*256)+bytes[3])/10,
    "596cb2638ecc890010075e52" : ((bytes[0]*256)+bytes[1])/10
  };
  return decoded;
}
```
What should I add in my "Dekodierungsoptionen"?

Although this is not very manageable and future proof, to add sensorID's to my decode function.
If I want to run 20 luftdaten sensors on Lora I can't add all the sensorID's to my application.

**Comment by noerw** [comment]
"Dekodierungsoptionen" (decode options)  for the `json` profile are ignored, as the decoding already happened on TTN side.

I agree on the lack of futureproofness. Currently the most robust way is to use the `lora-serialization` profile, and mapping the sensors via their name property, removing the need to explicitly specify the sensorIds.

The plan for the next iteration of this integration is to also let the TTN application be managed by this integration, allowing an automated TTN setup just with one registration on openSenseMap. The concept is explained in #8.

**Comment by noerw** [comment]
https://github.com/sensebox/openSenseMap/commit/71f4339daef49a42ac22b8e199ee1fc3b4d82133
should be online soon

**Comment by Cinezaster** [comment]
Still no data on the map:
Integration settings:
![schermafbeelding 2017-07-19 om 15 28 25](https://user-images.githubusercontent.com/188269/28369131-feeb844a-6c96-11e7-98f1-c28d2f76e63f.png)
payload decoder:
![schermafbeelding 2017-07-19 om 15 29 26](https://user-images.githubusercontent.com/188269/28369189-2bbcddac-6c97-11e7-8c08-c85d5643fa07.png)
openSenseMap configuration:
![schermafbeelding 2017-07-19 om 15 31 16](https://user-images.githubusercontent.com/188269/28369316-8587796e-6c97-11e7-8e7b-fbab9cd849ad.png)

And in the ttn data console:
![schermafbeelding 2017-07-19 om 15 33 27](https://user-images.githubusercontent.com/188269/28369359-a64e70e4-6c97-11e7-8811-7b0611dba0e5.png)

The only thing I don't know is the integration settings headers or authorization

**Comment by noerw** [comment]
Your configuration and payload function seem to be fine. There is no authorization header required.

We are receiving messages resulting in 404 errors, meaning that no box can be matched to the recieved `dev_id` & `app_id`. Are you sure that the values do match exactly in both openSenseMap and TTN configuration?

**Comment by Cinezaster** [comment]
Yes, I checked them again. And i'm using the copy function in the console.

![schermafbeelding 2017-07-19 om 17 04 26](https://user-images.githubusercontent.com/188269/28374228-6d72fab2-6ca4-11e7-9ad2-a86cb245c54c.png)

**Comment by Cinezaster** [comment]
Got it it is not the EUI but the name I gave it in TTN (they call it the id)
